version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - rblaine95

  # Maintain dependencies for Rust
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    assignees:
      - rblaine95

  # Maintain dependencies for Devcontainers
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
